If we run test.pl with -K we check the known bugs fail
Added this step to the test-script makefile as this has behaviour that
should fail the test (since it is testing the test.pl)

diff --git a/regression/test-script/Makefile b/regression/test-script/Makefile
--- a/regression/test-script/Makefile
+++ b/regression/test-script/Makefile
@@ -7,9 +7,23 @@ test:
 		exit 1; \
 	fi
 
+	@echo "Testing KNOWNBUG fail"
+
+	@if ! ../test.pl -c ../program_runner.sh -K ; then \
+		../failed-tests-printer.pl ; \
+		exit 1; \
+	fi
+
 tests.log:
 	pwd
 	@if ! ../test.pl -c ../program_runner.sh ; then \
+		../failed-tests-printer.pl ; \
+		exit 1; \
+	fi
+
+	@echo "Testing KNOWNBUG fail"
+
+	@if ! ../test.pl -c ../program_runner.sh -K ; then \
 		../failed-tests-printer.pl ; \
 		exit 1; \
 	fi
