Use vmactions
This appears to have much better performance (FreeBSD job completes in
26 minutes instead of 4 hours). We can now also enable the same number
of steps in OpenBSD and NetBSD.

diff --git a/.github/workflows/bsd.yaml b/.github/workflows/bsd.yaml
--- a/.github/workflows/bsd.yaml
+++ b/.github/workflows/bsd.yaml
@@ -6,7 +6,7 @@ on:
     branches: [ develop ]
 
 jobs:
-  # This job takes approximately X to Y minutes
+  # This job takes approximately 6 to 26 minutes
   FreeBSD:
     runs-on: ubuntu-latest
     steps:
@@ -26,19 +26,20 @@ jobs:
           echo "CCACHE_BASEDIR=$PWD" >> $GITHUB_ENV
           echo "CCACHE_DIR=$PWD/.ccache" >> $GITHUB_ENV
       - name: Build and Test
-        uses: cross-platform-actions/action@v0.21.1
+        uses: vmactions/freebsd-vm@v1
         with:
-          operating_system: freebsd
-          version: '13.2'
-          hypervisor: qemu
+          release: 13.2
+          usesh: true
           run: |
+            # apparently fail-on-error isn't the default here
+            set -e -x
             echo "Fetch dependencies"
-            sudo pkg install -y bash gmake git www/p5-libwww python python3 patch flex bison ccache parallel cvc5 z3
+            pkg install -y bash gmake git www/p5-libwww python python3 patch flex bison ccache parallel cvc5 z3
             echo "Fetch JBMC dependencies"
-            sudo pkg install -y openjdk8 wget maven
+            pkg install -y openjdk8 wget maven
             echo "Zero ccache stats and limit in size"
-            setenv CCACHE_BASEDIR $PWD
-            setenv CCACHE_DIR $PWD/.ccache
+            export CCACHE_BASEDIR=$PWD
+            export CCACHE_DIR=$PWD/.ccache
             ccache -z --max-size=500M
             ccache -p
             echo "Build with gmake"
@@ -57,7 +58,6 @@ jobs:
             gmake -C unit test
             # gmake -C jbmc/unit test
             echo "Running expected failure tests"
-            set histchars
             gmake TAGS='[!shouldfail]' -C unit test
             # gmake TAGS='[!shouldfail]' -C jbmc/unit test
             echo "Run regression tests"
@@ -67,7 +67,7 @@ jobs:
             # env PATH=$PATH:`pwd`/src/solvers gmake -C regression/cbmc test-cprover-smt2
             # # gmake -C jbmc/regression test-parallel JOBS=2
 
-  # This job takes approximately X to 34 minutes
+  # This job takes approximately 7 to 34 minutes
   OpenBSD:
     runs-on: ubuntu-latest
     steps:
@@ -87,49 +87,48 @@ jobs:
           echo "CCACHE_BASEDIR=$PWD" >> $GITHUB_ENV
           echo "CCACHE_DIR=$PWD/.ccache" >> $GITHUB_ENV
       - name: Build and Test
-        uses: cross-platform-actions/action@v0.21.1
+        uses: vmactions/openbsd-vm@v1
         with:
-          operating_system: openbsd
-          version: '7.4'
-          hypervisor: qemu
+          release: 7.4
           run: |
+            # apparently fail-on-error isn't the default here
+            set -e -x
             echo "Fetch dependencies"
-            sudo pkg_add -v bash gmake llvm%16 git python3 bison ccache parallel z3
-            sudo ln -s $(which llvm-ar-16) /usr/local/bin/llvm-ar
+            pkg_add -v bash gmake llvm%16 git python3 bison ccache parallel z3
+            ln -s $(which llvm-ar-16) /usr/local/bin/llvm-ar
             echo "Fetch JBMC dependencies"
-            sudo pkg_add -v jdk%1.8 wget maven
+            pkg_add -v jdk%1.8 wget maven
             echo "Zero ccache stats and limit in size"
             export CCACHE_BASEDIR=$PWD
             export CCACHE_DIR=$PWD/.ccache
             ccache -z --max-size=500M
             ccache -p
             echo "Build with gmake"
+            # don't do JBMC so as to keep the overall time in check
             gmake -C src minisat2-download
-            # we only build util.a to keep job execution time in check
-            gmake -C src -j2 CXX="ccache clang++" util.dir
-            # # don't do JBMC so as to keep the overall time in check
-            # gmake -C src -j2 CXX="ccache clang++"
-            # # gmake -C jbmc/src setup-submodules
-            # # gmake -C jbmc/src -j2 CXX="ccache clang++"
-            # gmake -C unit "CXX=ccache clang++"
-            # # gmake -C jbmc/unit "CXX=ccache clang++"
-            # echo "Print ccache stats"
-            # ccache -s
-            # echo "Checking completeness of help output"
-            # scripts/check_help.sh clang++
-            # echo "Run unit tests"
-            # gmake -C unit test
-            # # gmake -C jbmc/unit test
-            # echo "Running expected failure tests"
-            # gmake TAGS='[!shouldfail]' -C unit test
-            # # gmake TAGS='[!shouldfail]' -C jbmc/unit test
-            # echo "Run regression tests"
+            gmake -C src -j2 CXX="ccache clang++"
+            # gmake -C jbmc/src setup-submodules
+            # gmake -C jbmc/src -j2 CXX="ccache clang++"
+            gmake -C unit "CXX=ccache clang++"
+            # gmake -C jbmc/unit "CXX=ccache clang++"
+            echo "Print ccache stats"
+            ccache -s
+            echo "Checking completeness of help output"
+            scripts/check_help.sh clang++
+            echo "Run unit tests"
+            gmake -C unit test
+            # gmake -C jbmc/unit test
+            echo "Running expected failure tests"
+            gmake TAGS='[!shouldfail]' -C unit test
+            # gmake TAGS='[!shouldfail]' -C jbmc/unit test
+            echo "Run regression tests"
+            gmake -C regression/cbmc test
             # gmake -C regression test-parallel JOBS=2
             # gmake -C regression/cbmc test-paths-lifo
             # env PATH=$PATH:`pwd`/src/solvers gmake -C regression/cbmc test-cprover-smt2
             # # gmake -C jbmc/regression test-parallel JOBS=2
 
-  # This job takes approximately X to 21 minutes
+  # This job takes approximately 6 to 29 minutes
   NetBSD:
     runs-on: ubuntu-latest
     steps:
@@ -149,43 +148,44 @@ jobs:
           echo "CCACHE_BASEDIR=$PWD" >> $GITHUB_ENV
           echo "CCACHE_DIR=$PWD/.ccache" >> $GITHUB_ENV
       - name: Build and Test
-        uses: cross-platform-actions/action@v0.21.1
+        uses: vmactions/netbsd-vm@v1
         with:
-          operating_system: netbsd
-          version: '9.3'
-          hypervisor: qemu
+          release: 9.3
           run: |
+            # apparently fail-on-error isn't the default here
+            set -e -x
             echo "Fetch dependencies"
-            export PATH=/usr/pkg/sbin:/usr/pkg/bin:$PATH
-            export PKG_PATH=https://cdn.netbsd.org/pub/pkgsrc/packages/NetBSD/amd64/9.3/All/
-            sudo pkgin -y install bash gmake git python311 patch flex bison ccache parallel z3
-            sudo ln -s $(which python3.11) /usr/pkg/bin/python3
+            pkg_add -v bash gmake git python311 patch flex bison ccache parallel z3 gcc10
+            ln -s $(which python3.11) /usr/pkg/bin/python3
+            export PATH=/usr/pkg/gcc10/bin:$PATH
             echo "Fetch JBMC dependencies"
-            sudo pkgin -y install openjdk8 wget apache-maven
+            pkg_add -v openjdk8 wget apache-maven
             echo "Zero ccache stats and limit in size"
             export CCACHE_BASEDIR=$PWD
             export CCACHE_DIR=$PWD/.ccache
             ccache -z --max-size=500M
             ccache -p
             echo "Build with gmake"
+            # don't do JBMC so as to keep the overall time in check
             gmake -C src minisat2-download
-            # we only build util.a to keep job execution time in check
-            gmake -C src -j2 CXX="ccache g++" util.dir
-            # # don't do JBMC so as to keep the overall time in check
-            # gmake -C src -j2 CXX="ccache g++"
-            # # gmake -C jbmc/src setup-submodules
-            # # gmake -C jbmc/src -j2 CXX="ccache g++"
-            # gmake -C unit "CXX=ccache g++"
-            # # gmake -C jbmc/unit "CXX=ccache g++"
-            # echo "Print ccache stats"
-            # ccache -s
-            # echo "Checking completeness of help output"
-            # scripts/check_help.sh g++
-            # echo "Run unit tests"
-            # # ignore failures for the moment
-            # gmake -C unit test
-            # # gmake -C jbmc/unit test
-            # echo "Running expected failure tests"
-            # gmake TAGS='[!shouldfail]' -C unit test
-            # # gmake TAGS='[!shouldfail]' -C jbmc/unit test
-            # echo "Run regression tests"
+            gmake -C src -j2 CXX="ccache g++"
+            # gmake -C jbmc/src setup-submodules
+            # gmake -C jbmc/src -j2 CXX="ccache g++"
+            gmake -C unit "CXX=ccache g++"
+            # gmake -C jbmc/unit "CXX=ccache g++"
+            echo "Print ccache stats"
+            ccache -s
+            echo "Checking completeness of help output"
+            scripts/check_help.sh g++
+            echo "Run unit tests"
+            gmake -C unit test
+            # gmake -C jbmc/unit test
+            echo "Running expected failure tests"
+            gmake TAGS='[!shouldfail]' -C unit test
+            # gmake TAGS='[!shouldfail]' -C jbmc/unit test
+            echo "Run regression tests"
+            gmake -C regression/cbmc test
+            # gmake -C regression test-parallel JOBS=2
+            # gmake -C regression/cbmc test-paths-lifo
+            # env PATH=$PATH:`pwd`/src/solvers gmake -C regression/cbmc test-cprover-smt2
+            # # gmake -C jbmc/regression test-parallel JOBS=2
